version: '3.5'

services:
  traefik:
    image: traefik:latest
    #command: --api.insecure=true --providers.docker
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
       proxy:
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=mycloudflare@xemaps.com
      - CF_DNS_API_TOKEN=hwxV8YttHAxRC-2CkmscbklCrnVSE6waXkKTAyNm
      # - CF_API_KEY=YOU_API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/arx/docker/appdata/Traefik/traefik-config/traefik.yml:/traefik.yml:ro
      - /home/arx/docker/appdata/Traefik/traefik-config/acme.json:/acme.json
      - /home/arx/docker/appdata/Traefik/traefik-config/config.yml:/config.yml:ro
      - /home/arx/docker/appdata/Traefik/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.mailhost.monster`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=arx:$$apr1$$HqXNF4tX$$4rLIACHe4WIzW1OPoCFUC0"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.mailhost.monster`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=mailhost.monster"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.mailhost.monster"
      - "traefik.http.routers.traefik-secure.service=api@internal"


networks:
  proxy:
    name: proxy
    external: true
